### ISSUE TITLE
lock usage in Chapter 8 example

### ISSUE THREAD

**Issue by randvis** [josiahcarlson/redis-in-action#12]
In Chapter 8 Twitter clone example, I think after acquiring the lock, if something goes wrong, the lock should be released before function returning.

For example, in listing 8.1, `if conn.hget('users:', llogin)`, the lock should be released before `return None`. What do you think about it?
Perhaps it's better to use a With Statement context manager so it's not necessary to explicitly release the lock in multiple places.

```python
def create_user(conn, login, name):
    llogin = login.lower()
    lock = acquire_lock_with_timeout(conn, 'user:' + llogin, 1) #A
    if not lock:                            #B
        return None                         #B

    if conn.hget('users:', llogin):         #C
        return None                         #C

    id = conn.incr('user:id:')              #D
    .......
```

**Comment by josiahcarlson** [comment]
Yes, this is a bug. Thank you for the report and pull request.

In practice it is definitely better to use a with statement and context manager, or even just a try/finally. I didn't use either of these in the book as a general rule primarily because I wanted the code to be more approachable to a non-Python audience. I will accept your PR and close this bug when I've got the errata ready to send to the publisher.

**Comment by randvis** [comment]
Yeah, it's much easier for people not familiar with Python to understand in this way.
