### ISSUE TITLE
A Scala version examples will be good

### ISSUE THREAD

**Issue by satansk** [josiahcarlson/redis-in-action#44]
Hi, your book is fantastic, I love it, and there's already examples of Python, Java and so on, how about a Scala version?

**Comment by josiahcarlson** [comment]
I wrote the Python because I know Python, among a collection of other languages.

Java, Node, Ruby, and Gawk versions were contributed by 3rd parties because I choose not to know those languages/runtimes for a collection of reasons. I don't know Scala, and I can't convince myself that it makes sense to learn any Java-runtime language, considering I've managed to avoid all of those for about 17 years already.

I'd be happy to accept Scala examples if you or someone else is interested in writing them.
