### ISSUE TITLE
java code of chapter03 is not existed 

### ISSUE THREAD

**Issue by takeNoodlesAndGo** [josiahcarlson/redis-in-action#52]

**Comment by josiahcarlson** [comment]
You are correct. Since that chapter was mostly about interacting with the Redis console and exploring a bit of what functions do, the author of the Java code didn't see a need to implement that part. Most of the interesting code is in the other chapters, which goes to chapter 9 for Java.

If you'd like to contribute something for chapters 3, 10, or 11, we would be happy to look over the PR.
