### ISSUE TITLE
Zincrby last two parameters order misplaced

### ISSUE THREAD

**Issue by buffyanamin** [josiahcarlson/redis-in-action#63]
There is a typo In chapter 5’s python code, function update_stats 
pipe.zincrby(destination, value, 'sum')   
Should be
pipe.zincrby(destination, 'sum', value)
The same as the other 2 zincr code.

**Comment by josiahcarlson** [comment]
There isn't a bug with the code, there is a bug with the choice in the revision of the Redis client to use, because this changed:
https://github.com/andymccurdy/redis-py/blob/2.10.6/redis/client.py#L1710
https://github.com/andymccurdy/redis-py/blob/3.0.0/redis/client.py#L2279

I've updated the requirements file to require version 3.0.0 or later, which should fix your issue.
